apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
spec:
  project: restapi
  source:
    repoURL: https://github.com/arthurk/argocd-example-install.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: distribution
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
