apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: restapi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dbanieles/argocd-test.git
    targetRevision: HEAD
    path: dev/restapi
  destination:
    server: https://kubernetes.default.svc
    namespace: distribution
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true