apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: restapi
spec:
  project: default
  source:
    repoURL: https://github.com/dbanieles/argocd-test.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://D927E17A7D817911A6D0CB2DFF394C57.gr7.us-east-1.eks.amazonaws.com
    namespace: distribution
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
