# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: demo-app
# spec:
#   project: restapi
#   source:
#     repoURL: https://github.com/dbanieles/argocd-test.git
#     targetRevision: HEAD
#     path: dev
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: distribution
#     syncOptions:
#       - CreateNamespace=true
#     automated:
#       selfHeal: true
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: restapi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dbanieles/argocd-test.git
    targetRevision: master
    path: dev/restapi
  destination:
    server: https://kubernetes.default.svc
    namespace: distribution
  sync:
    comparedTo:
      source:
        repoURL: https://github.com/dbanieles/argocd-test.git
        targetRevision: master
        path: dev/restapi
      destination:
        server: https://kubernetes.default.svc
        namespace: distribution
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true