apiVersion: v1
kind: Secret
metadata:
  name: job-db-migrations-config
type: Opaque
stringData:
  POSTGRES_URL: "postgres.database"
  POSTGRES_USER: "postgresadmin"
  POSTGRES_PASSWORD: "admin"
  BOOTSTRAP: ""